### ISSUE TITLE
[FEATURE] CORS 허용 수정

### ISSUE THREAD

**Issue by sujnkim** [ToonInUs/Back#32]
# ISSUS: ✅FEATURE
---

## Description
---
#24 에서 구현한 CORS 코드에 문제가 발생하여 merge를 revert하였다.
이미 구현했었던 사항에서 오류를 수정하여 재업로드 할 것

## Todo
---
- [x] cors 패키지 install
- [x] white list (allowdOrigins.js) 작성
- [x] corsOptions 작성
- [x] app.js에 패키지 import
- [x] app.js cors 미들웨어 설정

## ETC
---
기타사항
