### ISSUE TITLE
[FEATURE]Model에 Schema 추가

### ISSUE THREAD

**Issue by song-na-min** [ToonInUs/Back#34]
# ISSUS: ✅FEATURE
---
model 추가

## Description
---
<br />이전 model/User.js에서 DB구조에 맞게 Schema를 수정하면서 ref한 것들이 없어서 문제 발생
=> 해당 ref 할 것들도 model을 생성하였다

<br />

## Todo
---
- [ ] Comment.js 추가
- [ ] Webtoon.js 추가
- [ ] Tag.js 추가

## ETC
---
User.js의 tagedwebtoons는 아직 구조를 확정하지 않았고, 사용하지 않기 때문에 주석처리 하였다. 추후 수정 후 사용 예정!
