### ISSUE TITLE
[FEATURE] Database 연결

### ISSUE THREAD

**Issue by sujnkim** [ToonInUs/Back#7]
# ISSUS: ✅FEATURE
---

## Description
---
Database에 연결하는 코드 작성
<br />
<br />

## Todo
---
- [x] MongoDB 사이트에서 DB 생성
- [x] DB 연결 함수 작성
- [x] DB 연결(app.js)

## ETC
---
기타사항
