### ISSUE TITLE
[FEATURE] 회원가입 기능

### ISSUE THREAD

**Issue by sujnkim** [ToonInUs/Back#9]
# ISSUS: ✅FEATURE
---

## Description
---
로그인 구현을 위해 회원 가입 라우터를 작성
<br />
<br />

## Todo
---
- [x] mongoose User Schema 생성
- [x] Role List 생성
- [x] 회원 가입 라우터 작성
- [x] 이메일, 닉네임 중복 확인 라우터 작성

## ETC
---
기타사항
